### ISSUE TITLE
-t command line parameter not considered

### ISSUE THREAD

**Issue by LiamHD** [jhitchcock/raml2wiki#14]
I tried to use my own custom template (via the "-t" parameter) But this is not considered during execution. It always takes the built-in template.

By the way "ram2wiki --help" does not list the "-t" , "-s"m "-r" and "-m" parmeters.
They are also not documented.

**Comment by jkollmer** [comment]
+1 here. I'd love to use a custom template, but don't see how. Am I missing something obvious? 

Thanks for your help!

**Comment by jkollmer** [comment]
Thanks for looking into this! In the meantime, I've just replaced the templates in /usr/local/lib/node_modules/raml2wiki/lib/ with my custom templates, which also does the trick (for OS X).

**Comment by jhitchcock** [comment]
Ok, so, Actually this doesnt support the -t (currently, I think It may do in the future as we gather alternative templates) so Ive removed it from the readme for now. Watch out for updates!
