### ISSUE TITLE
jsonschemas internal reference {$ref} do not get resolved.

### ISSUE THREAD

**Issue by avalencia** [jhitchcock/raml2wiki#15]
When the RAML file reference some json schema, the schema get included in the generated Confluence ML. but if the schema contains {$ref} sections, including external schemas, the generated document is not resolving the references and leaving the {$ref}, would be great if this references get resolved recursively, so is easy to have a full view of the schema on Confluence.

an example of the json schema would be 

                        "location": {
                            "$ref": "file:src/main/resources/location.schema"
                        }

**Comment by jhitchcock** [comment]
Added support for $ref inline with raml2html 0.2.0
