### ISSUE TITLE
securitySchemes

### ISSUE THREAD

**Issue by jcichoski** [jhitchcock/raml2wiki#18]
Is the security portion of RAML implemented in the conversion? It seems "securitySchemes:" and "securedBy:" tokens and containing descriptors are ignored. At first, I considered that my RAML's security portion may have needed some work, however, I tried to convert the security portion explicitly from the repository example and the resulting text file is missing it as well.

**Comment by jhitchcock** [comment]
Added SecuredBy tags to methods in 0.2.0
