### ISSUE TITLE
Can't covert the txt file to wiki markup

### ISSUE THREAD

**Issue by sarashvand** [jhitchcock/raml2wiki#20]
I follow the ReadMe instruction. when I created a txt file from RAML file, and entered the content in a wiki, I got the following error.

please assist

error:
"
Wiki markup conversion errors

The server took too long to convert the wiki markup. This may only be a temporary problem so you could try again.
"

**Comment by jhitchcock** [comment]
Please let me see the Wiki markup generated, or if its confidential, try validating it at another resource and let me know which part is the issue

**Comment by jhitchcock** [comment]
Closing since no further info and cannot replicate
