### ISSUE TITLE
Raml 1.0 support

### ISSUE THREAD

**Issue by ypppa** [jhitchcock/raml2wiki#21]
```
Error parsing: version validation
Unsupported RAML version: '#%RAML 1.0'
  in "api.raml", line 1, column 1:
    #%RAML 1.0
              ^
```

**Comment by neilhosey** [comment]
Is

**Comment by jhitchcock** [comment]
Hey, I'm not planning on implementing RAML 1.0 support for some time, in the meantime there is a workaround they are using on the RAML2 HTML; 

https://github.com/raml2html/raml2html/issues/156
