### ISSUE TITLE
Headers do not show up

### ISSUE THREAD

**Issue by johnjkk** [jhitchcock/raml2wiki#23]
I added headers such as

 headers:
         Content-Type:
           default: application/json
         Content-Length:
           example: 50
         Last-Modified:
           example: 2016-04-14T16:50:10.000Z

But in wiki it just comes as:

headers
headers
headers

**Comment by mosesonline** [comment]
For me especially response headers, i.e. "Location" after a POST, is a must have. As a workaround I have to modify the document manually.

**Comment by jhitchcock** [comment]
Fixed in 0.2.0
