### ISSUE TITLE
silently finishes without any output

### ISSUE THREAD

**Issue by danielb2** [jhitchcock/raml2wiki#3]
I'm not sure what's going on, but I ran it `raml2wiki groceries.raml` and it doesn't produce any  output

``` raml
#%RAML 0.8
title:
/cart:
  /{id}:
  /product:
    /{productId}:
      post:
        description: Adding a product to a cart
```

**Comment by jhitchcock** [comment]
Thnks for the issue. I'll look into it ASAP and update here

**Comment by jhitchcock** [comment]
oops. didnt mean to close it

**Comment by jhitchcock** [comment]
Sorry for the delay again. Will also fix this this weekend :)

**Comment by jhitchcock** [comment]
Thanks for highlighting this. Bug spotted and fixed  :)
