### ISSUE TITLE
installation won't work in Linux Mint (Ubuntu-based)

### ISSUE THREAD

**Issue by resilva87** [jhitchcock/raml2wiki#4]
As [reported by @danielb2](https://github.com/jhitchcock/raml2wiki/issues/2), I cannot run raml2wiki:

renato@renato-pc ~/Workspace/Playground $ raml2wiki stuff.raml
: No such file or directory

Tried installing and running dos2unix node_modules/.bin/raml2wiki as @jraede has recommended, but didnt' do the trick.

Can anyone verify this please?

Thanks a lot!

**Comment by jraede** [comment]
Sorry the file in bin is just a symlink, you have to run that on the actual
executable file in node_modules/raml2wiki

**Comment by resilva87** [comment]
alright that worked like a charm :)
thanks @jraede !!
