### ISSUE TITLE
raml2wiki produces empty .txt fijle

### ISSUE THREAD

**Issue by djr303** [jhitchcock/raml2wiki#5]
Hi

I've just install raml2wiki globally but when using the command: raml2wiki example.raml > example.txt

But it produces an empty text file, am I doing something wrong?

**Comment by vemod** [comment]
same here

**Comment by o-l-o** [comment]
I experienced the same issue

**Comment by zentoaku** [comment]
I've experienced this and was able to solve by double checking raml file. In my case it was some attribute used in wrong (not allowed) place. We would really use some validation output :)

**Comment by jhitchcock** [comment]
Could be that. I'll look into it and add an example RAML file. 

What's the example RAML file you are using out of interest?

**Comment by djr303** [comment]
hi tried the RAML example on raml.org:

#%RAML 0.8

title: World Music API
baseUri: http://example.api.com/{version}
version: v1
traits:
  - paged:
      queryParameters:
        pages:
          description: The number of pages to return
          type: number
  - secured: !include http://raml-example.com/secured.yml
/songs:
  is: [ paged, secured ]
  get:
    queryParameters:
      genre:
        description: filter the songs by genre
  post:
  /{songId}:
    get:
      responses:
        200:
          body:
            application/json:
              schema: |
                { "$schema": "http://json-schema.org/schema",
                  "type": "object",
                  "description": "A canonical song",
                  "properties": {
                    "title":  { "type": "string" },
                    "artist": { "type": "string" }
                  },
                  "required": [ "title", "artist" ]
                }
            application/xml:
    delete:
      description: |
        This method will *delete* an **individual song**

**Comment by djr303** [comment]
#%RAML 0.8

title: World Music API
baseUri: http://example.api.com/{version}
version: v1
traits:
  - paged:
      queryParameters:
        pages:
          description: The number of pages to return
          type: number
  - secured: !include http://raml-example.com/secured.yml
/songs:
  is: [ paged, secured ]
  get:
    queryParameters:
      genre:
        description: filter the songs by genre
  post:
  /{songId}:
    get:
      responses:
        200:
          body:
            application/json:
              schema: |
                { "$schema": "http://json-schema.org/schema",
                  "type": "object",
                  "description": "A canonical song",
                  "properties": {
                    "title":  { "type": "string" },
                    "artist": { "type": "string" }
                  },
                  "required": [ "title", "artist" ]
                }
            application/xml:
    delete:
      description: |
        This method will *delete* an **individual song**

**Comment by djr303** [comment]
sorry that coming in a markdown, but it was pure YAML: http://raml.org/

**Comment by chavdarb** [comment]
I am having similar experiences with raml2wiki. It is not generating any example or schema in the output. It does not output any error or hint ..

**Comment by jhitchcock** [comment]
I have added an error callback, and also an example RAML file. This example file above is not valid RAML and now errors out.
