### ISSUE TITLE
raml2wiki can't convert to text file!

### ISSUE THREAD

**Issue by ahjdzx** [jhitchcock/raml2wiki#6]
example:
```
$ raml2wiki example_github.raml > example.txt
: No such file or directory
```

**Comment by y0an** [comment]
same error for me, but my raml-cop, raml2md & raml2html works fine! :(

**Comment by jhitchcock** [comment]
Have updated the npm. I don't have a mac handy to test but I just run it in a linux terminal with no issues . Can you test the version just published? 

james@lo1:/home$ sudo npm install -g raml2wiki
[sudo] password for james: 
/usr/bin/raml2wiki -> /usr/lib/node_modules/raml2wiki/lib/raml2wiki.js
raml2wiki@0.1.6 /usr/lib/node_modules/raml2wiki
├── commander@2.8.1 (graceful-readlink@1.0.1)
├── handlebars@2.0.0 (optimist@0.3.7, uglify-js@2.3.6)
└── raml2obj@0.3.0 (raml-parser@0.8.11)
james@lo1:/home$ raml2wiki
Error: You need to specify the RAML input file

  Usage: raml2wiki [options] [RAML input file]

  Options:

    -h, --help             output usage information
    -i, --input [input]    RAML input file
    -o, --output [output]  Wiki Markup output file

**Comment by y0an** [comment]
Fixed! 
thanks you @jhitchcock
