### ISSUE TITLE
Can't get raml2wiki to work from command line on a Mac

### ISSUE THREAD

**Issue by TimothyMDean** [jhitchcock/raml2wiki#7]
I can run `raml2wiki` just fine from a Windows PC, but when I try to run from the command-line on my Mac it fails as follows:

    tims-mbp:VSP tdean$ raml2wiki eventPublishing.raml > eventPublishing.txt
    env: node\r: No such file or directory

I get this same message even if I run with no command-line arguments:

    tims-mbp:VSP tdean$ raml2wiki
    env: node\r: No such file or directory

My initial reaction is that there must be something wrong with my node setup on this machine. However, I do not get the same problem when running `raml2html` or other node modules. For example:

    tims-mbp:lib tdean$ raml2html
    Error: You need to specify the RAML input file
    
      Usage: raml2html [options] [RAML input file]

      Options:

        -h, --help                 output usage information
        -V, --version              output the version number
        -i, --input [input]        RAML input file
        -s, --https                Use https links in the generated output
        -o, --output [output]      HTML output file
        -t, --template [template]  Path to custom template.handlebars file
        -r, --resource [resource]  Path to custom resource.handlebars file
        -m, --item [item]          Path to custom item.handlebars file

I'm not sure what the difference could be between these two different node modules, but it appear to be something unique within the installation of the `raml2wiki` module.

**Comment by TimothyMDean** [comment]
This looks to be the same as issue #2 but I am seeing it on version 0.1.5 even though that issue was supposedly fixed in version 0.1.3

**Comment by jhitchcock** [comment]
Hey. What makes you think its the same issue? Not saying it isn't, just wondering! 

Also, are you installing it with npm install -g raml2wiki? 

What's the result of running; 

npm root -g

?

**Comment by TimothyMDean** [comment]
I assume it was the same issue because the workaround suggested in issue #2 (using the dos2unix command) fixed the problem for me.

I had installed using "npm install -g raml2wiki"

The result of running “nom root -g” is:

/usr/local/lib/node_modules

-Tim

**Comment by jhitchcock** [comment]
Have updated the npm. I don't have a mac handy to test but I just run it in a linux terminal with no issues 

james@lo1:/home$ sudo npm install -g raml2wiki
[sudo] password for james: 
/usr/bin/raml2wiki -> /usr/lib/node_modules/raml2wiki/lib/raml2wiki.js
raml2wiki@0.1.6 /usr/lib/node_modules/raml2wiki
├── commander@2.8.1 (graceful-readlink@1.0.1)
├── handlebars@2.0.0 (optimist@0.3.7, uglify-js@2.3.6)
└── raml2obj@0.3.0 (raml-parser@0.8.11)
james@lo1:/home$ raml2wiki
Error: You need to specify the RAML input file

  Usage: raml2wiki [options] [RAML input file]

  Options:

    -h, --help             output usage information
    -i, --input [input]    RAML input file
    -o, --output [output]  Wiki Markup output file

**Comment by TimothyMDean** [comment]
I have done a fresh install of the npm on my Mac and confirmed that the issue is fixed.

**Comment by jhitchcock** [comment]
excellent, thanks for raising it and confirming fix
