### ISSUE TITLE
Request body schema and example missing

### ISSUE THREAD

**Issue by lgustafson** [jhitchcock/raml2wiki#8]
The output of raml2wiki does not appear to include the request body "schema" or "example" properties as it does for responses.

**Comment by jhitchcock** [comment]
Very good point! 

I shall add it this week!

**Comment by lgustafson** [comment]
I'm in the process of submitting a PR for this issue

**Comment by jhitchcock** [comment]
Oh, even better! :D

**Comment by jhitchcock** [comment]
Many thanks for your pull requests. All merged in! 

Will update NPM tomorrow

**Comment by lordfriend** [comment]
Request Body  Example still missing

**Comment by lgustafson** [comment]
I don't believe that the npm was every updated, so if you are using it that would be the reason.

**Comment by jhitchcock** [comment]
You are quite right @lgustafson Apologies @lordfriend 

Version 0.1.7 has now been pushed to NPM
